[build-system]
requires = ["setuptools", "wheel"]
[project]
name = "deaduction"
dynamic = ["dependencies", "version"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {file = ".git/HEAD"}
